# Generated by Django 5.0.6 on 2024-06-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendamento', '0002_salas_usuario_agendamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='agendado_por',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
